import ProductModal from "@/components/ProductModal/_ProductModal";
import Footer from "./_components/Footer";
import Navbar from "./_components/Navbar/_Navbar";
import "./globals.css";

import { Raleway } from 'next/font/google'
import { Toaster } from "sonner";


const font =  Raleway({ subsets: ['latin'] })

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
      <html lang="en">  
        <body className={`${font.className} antialiased`}>
          <Toaster />
          <ProductModal />

          <div className="space-y-6">
            <header className="container-full-content border-b 
            border-gray-200 sticky top-0 z-30 bg-white"
            >
              <Navbar/>
            </header>

            <main className="container-full-content">
              <div className="container">
              {children}
              </div>
            </main>

            <Footer/>
          </div>
          
        </body>
      </html>
  );
}
